FROM hypriot/rpi-golang

RUN mkdir -p /go/src/app
RUN mkdir -p /var/lib/etcd
WORKDIR /go/src/app

# this will ideally be built by the ONBUILD below ;)
CMD ["go-wrapper", "run"]

COPY . /go/src/app
RUN mv /go/src/app/go-wrapper /goroot/bin/go-wrapper
RUN chmod +x /goroot/bin/go-wrapper
RUN go-wrapper download
RUN go-wrapper install

ENTRYPOINT ["etcd"]

EXPOSE 4001 7001 2379 2380
